<?php
// controllers/RestockAlert.php

class RestockAlert {
    
    // Custom logging function
    private static function writeLog($message) {
        $logDir = __DIR__ . '/../logs';
        if (!is_dir($logDir)) {
            @mkdir($logDir, 0755, true);
        }
        $logFile = $logDir . '/email_debug.log';
        $time = date('Y-m-d H:i:s');
        @file_put_contents($logFile, "[$time] " . $message . PHP_EOL, FILE_APPEND);
    }

    private static function generateEmailHTML($part) {
        return <<<HTML
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f4f4f5; margin: 0; padding: 40px 0; -webkit-font-smoothing: antialiased; }
                .container { max-width: 540px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05); border: 1px solid #e4e4e7; }
                .header { background-color: #ffffff; padding: 30px 40px 20px; text-align: center; border-bottom: 1px solid #f4f4f5; }
                .header h1 { margin: 0; color: #18181b; font-size: 22px; font-weight: 800; letter-spacing: -0.5px; }
                .body { padding: 40px; color: #3f3f46; font-size: 16px; line-height: 1.6; }
                .alert-box { background: #fffbeb; border: 1px solid #fde68a; border-radius: 12px; padding: 20px; text-align: center; margin: 25px 0; }
                .alert-title { color: #92400e; font-size: 14px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; display: block; }
                .alert-stock { color: #b45309; font-size: 32px; font-weight: 900; line-height: 1; display: block; }
                .footer { background-color: #fafafa; padding: 24px 40px; text-align: center; font-size: 13px; color: #a1a1aa; border-top: 1px solid #e4e4e7; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Norily's Repair Shop</h1>
                </div>
                <div class="body">
                    <p>Hello <strong>{$part['supplier_name']}</strong>,</p>
                    <p>This is a notification from our inventory system. Our stock for <strong>{$part['part_name']}</strong> requires restocking.</p>
                    <div class="alert-box">
                        <span class="alert-title">Current Inventory Level</span>
                        <span class="alert-stock">{$part['quantity_on_hand']} left</span>
                    </div>
                    <p>Please arrange a restock delivery at your earliest convenience. We will follow up shortly if a formal purchase order is required.</p>
                    <p>Thank you,<br>Norily's Vehicle Repair Shop Team</p>
                </div>
                <div class="footer">
                    <p>This is an automated alert generated by DASPMS.</p>
                </div>
            </div>
        </body>
        </html>
        HTML;
    }

    /**
     * Called automatically by system. Fails silently but logs errors.
     */
    public static function checkAndSend($db, $part_id) {
        try {
            $stmt = $db->prepare("SELECT p.part_name, p.quantity_on_hand, p.low_stock_threshold, s.supplier_name, s.email FROM part p JOIN supplier s ON p.supplier_id = s.supplier_id WHERE p.part_id = ? AND p.is_active = 1 AND s.is_active = 1");
            $stmt->execute([intval($part_id)]);
            $part = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($part && !empty($part['email']) && intval($part['quantity_on_hand']) <= intval($part['low_stock_threshold'])) {
                self::writeLog("AUTO-TRIGGER: Threshold reached for {$part['part_name']}. Attempting to email {$part['email']}...");
                
                $headers = "MIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\nFrom: Norily's Repair Shop <daspms1998@gmail.com>\r\nReply-To: daspms1998@gmail.com\r\nX-Mailer: PHP/" . phpversion();
                $message = self::generateEmailHTML($part);
                
                if (@mail($part['email'], "Restock Request: " . $part['part_name'], $message, $headers)) {
                    self::writeLog("AUTO-TRIGGER: SUCCESS - Email handed to sendmail.");
                } else {
                    $error = error_get_last();
                    self::writeLog("AUTO-TRIGGER: FAILED - " . ($error['message'] ?? 'Unknown SMTP error'));
                }
            }
        } catch (Exception $e) {
            self::writeLog("AUTO-TRIGGER: SYSTEM ERROR - " . $e->getMessage());
        }
    }

    /**
     * Called by manual button. Forces email and returns feedback to UI.
     */
    public static function manualSend($db, $part_id) {
        try {
            $stmt = $db->prepare("SELECT p.part_name, p.quantity_on_hand, p.low_stock_threshold, s.supplier_name, s.email FROM part p JOIN supplier s ON p.supplier_id = s.supplier_id WHERE p.part_id = ?");
            $stmt->execute([intval($part_id)]);
            $part = $stmt->fetch(PDO::FETCH_ASSOC);

            if (!$part) return ['success' => false, 'message' => 'Part not found.'];
            if (empty($part['email'])) return ['success' => false, 'message' => 'No supplier email linked to this part.'];

            self::writeLog("MANUAL: Attempting to email {$part['email']} for {$part['part_name']}...");

            $headers = "MIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\nFrom: Norily's Repair Shop <daspms1998@gmail.com>\r\nReply-To: daspms1998@gmail.com\r\nX-Mailer: PHP/" . phpversion();
            $message = self::generateEmailHTML($part);

            if (@mail($part['email'], "Restock Request: " . $part['part_name'], $message, $headers)) {
                self::writeLog("MANUAL: SUCCESS - Email sent.");
                return ['success' => true, 'message' => "Restock alert successfully sent to {$part['supplier_name']}!"];
            } else {
                $error = error_get_last();
                $errDetail = $error['message'] ?? 'Unknown SMTP routing error';
                self::writeLog("MANUAL: FAILED - " . $errDetail);
                return ['success' => false, 'message' => "Failed to send email. Check logs. Detail: " . $errDetail];
            }
        } catch (Exception $e) {
            self::writeLog("MANUAL: SYSTEM ERROR - " . $e->getMessage());
            return ['success' => false, 'message' => 'Database error during email dispatch.'];
        }
    }
}
?>